# Generated by Django 4.2.20 on 2025-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="audio_file",
            field=models.FileField(upload_to="audios/"),
        ),
    ]
