# Generated by Django 4.2.20 on 2025-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_transcription_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="audio_file",
            field=models.BinaryField(),
        ),
    ]
