# Generated by Django 5.2 on 2025-04-22 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_uploadedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                upload_to="uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav", "ogg", "flac", "aac"]
                    )
                ],
            ),
        ),
    ]
