# Generated by Django 5.2 on 2025-04-23 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="audio_file",
            field=models.FileField(
                upload_to="uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav", "ogg", "flac", "aac"]
                    )
                ],
            ),
        ),
    ]
