# Generated by Django 5.2 on 2025-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_transcription_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="transcript_file",
            field=models.FileField(blank=True, null=True, upload_to="transcripts/"),
        ),
    ]
