version: '3'

services:
  db:
    image: postgres:13
    container_name: asr_transcriber-db-1
    environment:
      POSTGRES_DB: asrdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: May20...
    volumes:
      - asr_transcriber_postgres_data:/var/lib/postgresql/data
    networks:
      - asr_network
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:May20...@db:5432/asrdata
    depends_on:
      - db
    networks:
      - asr_network

  frontend:
    build:
      context: ./asr-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - asr_network

networks:
  asr_network:
    driver: bridge

volumes:
  asr_transcriber_postgres_data:
