services:
  - type: web
    name: backend
    runtime: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: |
      cd backend
      gunicorn your_project_name.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asrdata
          property: connectionString