<<<<<<< HEAD
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
=======
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
>>>>>>> 90e99aa7fb7bd33fa04a3c41ec3e1fceaa2bdf3e

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-kl5n(z=r3rx-ge_wi-li9^4uq9%d+@2=91nh=ln8hix4%c(@fr"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
<<<<<<< HEAD
ALLOWED_HOSTS = []

# Application definition
=======

ALLOWED_HOSTS = []


# Application definition

>>>>>>> 90e99aa7fb7bd33fa04a3c41ec3e1fceaa2bdf3e
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
<<<<<<< HEAD
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'api',
=======
    'api',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',

    
>>>>>>> 90e99aa7fb7bd33fa04a3c41ec3e1fceaa2bdf3e
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
<<<<<<< HEAD
    "corsheaders.middleware.CorsMiddleware",  # Move above CommonMiddleware
=======
>>>>>>> 90e99aa7fb7bd33fa04a3c41ec3e1fceaa2bdf3e
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
<<<<<<< HEAD
]
=======
    'corsheaders.middleware.CorsMiddleware',



]
CORS_ALLOW_ALL_ORIGINS = True
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
CORS_ALLOW_ALL_ORIGINS = True
>>>>>>> 90e99aa7fb7bd33fa04a3c41ec3e1fceaa2bdf3e

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

<<<<<<< HEAD
# PostgreSQL Database setup
=======

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

>>>>>>> 90e99aa7fb7bd33fa04a3c41ec3e1fceaa2bdf3e
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'asrdata',
        'USER': 'postgres',
<<<<<<< HEAD
        'PASSWORD': 'May20...',  # Replace with actual password
=======
        'PASSWORD': 'May20...',  # jo bhi tumne postgres install time pe diya tha
>>>>>>> 90e99aa7fb7bd33fa04a3c41ec3e1fceaa2bdf3e
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

<<<<<<< HEAD
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Media files (for uploaded audio/transcriptions)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# DRF JWT Authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Allow all CORS (only in dev; restrict in production)
CORS_ALLOW_ALL_ORIGINS = True

# Default primary key field type
=======




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

>>>>>>> 90e99aa7fb7bd33fa04a3c41ec3e1fceaa2bdf3e
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
